### ISSUE TITLE
Export path as gpx

### ISSUE THREAD

**Issue by bmidgley** [bmidgley/mars-evalink#2]
Currently exported in json which nothing can use directly

**Comment by bmidgley** [comment]
done

**Comment by kristoe** [comment]
@bmidgley how are EVA's filtered / searched for?

**Comment by bmidgley** [comment]
@kristoe for the record, we can search using location: https://github.com/bmidgley/mars-evalink/issues/55

searching by timeframe or crew would be nice but we can't do it yet.
